### ISSUE TITLE
Don't use dateValues

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/dwca-validator#6]
It is a bit odd to make `dateValues` a "subfunction" that alters the functionality of `range` and `equals`:

```YAML
dateValues:
- equals: [YYYY-MM-DD, YYYY-MM, YYYY] # Will match specific date formats
- range: [1830-01-01, 2014-10-20] # Will match dates between specific date range (inclusive)
```

In contrast with `delimitedValues` (which changes the scope) and `if` (which makes the tests conditions), `dateValues` wouldn't really alter other functions, such as `unique` etc.

I would propose to use:

* `dateFormat: [YYYY-MM-DD, YYYY-MM, YYYY]` It is a formatting thing, not an `equals` thing anyway and we already have `numberFormat`.
* `dateRange: [1830-01-01, 2014-10-20]`
* `numberRange: [0,1]` For consistency. And it only applies to numbers anyway.
