### ISSUE TITLE
Should `equals` ignore empty values?

### ISSUE THREAD

**Issue by peterdesmet** [LifeWatchINBO/dwca-validator#7]
In some cases, like `stateProvince` it makes sense to do:

```YAML
stateProvince:
    - equals: [Antwerp, Brussels Capital Region, East Flanders, Flemish Brabant, Limburg, West Flanders]
```

... which expects specific values, but allows blanks.

But in a lot of cases one wants to test `equals` and not accept empty values. This is done by combining `equals` and `populated`:

1. This allows for more flexibility, but users have to remember to test for both, otherwise `equals` will silently ignore all empty values. A single combined test might be more intuitive.
2. These are tested independent from each other. So `equals` can pass, while `populated` will fail.
3. In `if` statements it might get complicated, as the conditions are combined with `AND`, but the tests are not:

```YAML
type:
    - if:
        - basisOfRecord:
            - populated: true 
            - equals: HumanObservation # Combined with test above with AND
        - populated: true # Separate test
        - equals: Event # Separate test
```

Proposals:

1. Leave it as it is for now, but ask feedback from outside users, like Dimi
2. Add `equalsAllowEmpty:` to be very explicit about it.
3. Add an extra parameter, e.g. `equals: HumanObservation, allow empty`

The decision should be consistent with other functions.

**Comment by stijnvanhoey** [comment]
When working with length (or minlength/maxlength), this empty possibility can also be confusing. For example:

```YAML
stateProvince:
    - minlength: 5
```
The latter would accept 'myword', but also '', which is rather strange if you provide minlength... 

An alternative strategy by creating a new rule: empty: True, which means empty values are allowed as well; However, this would still require an order in the evaluation to decide what would happen if the user provides following scheme:

```YAML
stateProvince:
    - minlength: 5
    - empty: True
```
Would it provide an error on minlength (independent from rule empty) or should it take the combination into account?
